version: "3"
services:
  package:
    image: natanfelles/package
    container_name: database-package
    working_dir: /package
    volumes:
      - .:/package
    depends_on:
      - mariadb
      - mysql
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: framework-tests
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    container_name: database-mariadb
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: framework-tests
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    container_name: database-mysql
